workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Pod install
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - "**/*.ipa"

  ios-adhoc:
    name: iOS Ad Hoc (Installable)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: ad_hoc
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Pod install
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
