name: money_management
description: "Aplikasi keuangan keluarga - tracking pengeluaran BCA"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.6.0
  cloud_firestore: ^6.2.0
  firebase_auth: ^6.3.0

  # State Management
  flutter_riverpod: ^2.6.1

  # Charts
  fl_chart: ^0.70.2

  # CSV, PDF & File
  csv: ^6.0.0
  file_picker: ^8.1.7
  syncfusion_flutter_pdf: ^27.2.5

  # HTTP
  http: ^1.2.0

  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1
  crypto: ^3.0.6
  google_sign_in: ^6.2.2
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
